@echo off
echo Deleting old binaries...
del /f slo.bin cdread.bin SLO-eur.img SLO-usa.img SLO-jap.img
echo Building SLO...
..\tools\asm68k /p slo.ASM, slo.bin && echo.
echo Building cdread...
..\tools\asm68k /p cdread.ASM, cdread.bin && echo.
echo Building final images...
copy /b assets\security-usa.bin + slo.bin + cdread.bin + assets\pad-6000h.bin SLO-usa.img
copy /b assets\security-jap.bin + slo.bin + cdread.bin + assets\pad-6000h.bin SLO-jap.img
copy /b assets\security-eur.bin + slo.bin + cdread.bin + assets\pad-6000h.bin SLO-eur.img
echo Done! && echo.